#!/usr/bin/env python
# -*- coding: utf-8 -*-
def try_me():
    answer = input("What's up for Sunday? ")
    if answer == 'golf':
        return 'CORRECT!'
    if answer != 'golf':
        return 'WRONG, GOLF!'

if __name__ == "__main__":
    print(try_me())
